/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace geospatial.thrift
{
  public enum FeatureState
  {
    CLEAN = 1,
    DIRTY = 2,
  }
}
