/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace geospatial.thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Rectangle : TBase
  {
    private Point _top_lt;
    private Point _btm_rt;

    public Point Top_lt
    {
      get
      {
        return _top_lt;
      }
      set
      {
        __isset.top_lt = true;
        this._top_lt = value;
      }
    }

    public Point Btm_rt
    {
      get
      {
        return _btm_rt;
      }
      set
      {
        __isset.btm_rt = true;
        this._btm_rt = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool top_lt;
      public bool btm_rt;
    }

    public Rectangle() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Top_lt = new Point();
              Top_lt.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              Btm_rt = new Point();
              Btm_rt.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Rectangle");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Top_lt != null && __isset.top_lt) {
        field.Name = "top_lt";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        Top_lt.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (Btm_rt != null && __isset.btm_rt) {
        field.Name = "btm_rt";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        Btm_rt.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Rectangle(");
      sb.Append("Top_lt: ");
      sb.Append(Top_lt== null ? "<null>" : Top_lt.ToString());
      sb.Append(",Btm_rt: ");
      sb.Append(Btm_rt== null ? "<null>" : Btm_rt.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
